#! /bin/sh

# Check the first argument passed to the script
case "$1" in
    start)
        # If the argument is "start", print a message and start the aesdsocket daemon
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- "-d"
        ;;
    stop)
        # If the argument is "stop", print a message and stop the aesdsocket daemon
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket --signal SIGTERM
        ;;
    *)
        # If the argument is not "start" or "stop", print usage information and exit with an error code
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

# Exit the script successfully
exit 0


